- backend/access_code.py
- backend/data_format.md
document action schema
[work item link](https://dev.azure.com/gt-sse-center/CoAuthor/_workitems/edit/674/)
> document action schema

- src/coauthor_interface/backend/api_server.py
- tests/test_api_server.py
Add tests for start_session api route
[Please include link to the corresponding GitHub Issue or Project work item.](https://dev.azure.com/gt-sse-center/CoAuthor/_workitems/edit/689/)
> 689 varun  add comprehensive tests

- tests/test_api_server.py
Test end_session route - successful call
https://dev.azure.com/gt-sse-center/CoAuthor/_workitems/edit/689/
> test end_session route, successful call

- tests/test_api_server.py
Adds tests to ensure session isolation for different session IDs
https://dev.azure.com/gt-sse-center/CoAuthor/_workitems/edit/689/
> test for session isolation

- pyproject.toml
- uv.lock
Add coverage info - note that the min coverage threshold is very low for now (35%) this will be incrementally bumped up as more tests are added
No work item
> add coverage info

- tests/test_api_server.py
> [689] adding couples of tests for query and get_log

- .gitignore
- pyproject.toml
- tests/test_api_server.py
- tests/test_helper.py
- uv.lock
add tests for helper functions
> 689 add helper tests 2

- pyproject.toml
- src/coauthor_interface/backend/api_server.py
- src/coauthor_interface/backend/helper.py
- src/coauthor_interface/backend/parse_all_consolidated.py
- src/coauthor_interface/backend/parsing.py
- src/coauthor_interface/backend/reader.py
- src/coauthor_interface/thought_toolkit/action_parser.py
- src/coauthor_interface/thought_toolkit/helper.py
- src/coauthor_interface/thought_toolkit/level_2_comparisons.py
- src/coauthor_interface/thought_toolkit/level_3_comparisons.py
- src/coauthor_interface/thought_toolkit/parser_all_levels.py
- src/coauthor_interface/thought_toolkit/parser_helper.py
- src/coauthor_interface/thought_toolkit/utils.py
- tests/test_api_server.py
- tests/test_helper.py
- tests/test_plugin.py
- uv.lock
- Move analysis code (previously commented out) into it's own file
- **This PR is only moving code into the github from onedrive and is not going into main**
Note:
- All files that have just been added are simply copied over from the OneDrive that was shared with us
- Analysis code was previously commented out and scattered in `src/coauthor_interface/thought_toolkit/parser_all_levels.py`
- This has been moved into `src/coauthor_interface/backend/parse_all_consolidated.py`
> Consolidate analysis into one file

- pyproject.toml
- src/coauthor_interface/backend/api_server.py
- src/coauthor_interface/backend/helper.py
- src/coauthor_interface/thought_toolkit/parser_all_levels.py
- src/coauthor_interface/thought_toolkit/parser_helper.py
- tests/test_api_server.py
- uv.lock
fix errors/tests from adding onedrive files
> Fix errors from adding onedrive files

- .github/workflows/standard.yaml
- pyproject.toml
- src/coauthor_interface/backend/api_server.py
- src/coauthor_interface/backend/helper.py
- src/coauthor_interface/backend/parse_all_consolidated.py
- src/coauthor_interface/backend/parsing.py
- src/coauthor_interface/backend/reader.py
- src/coauthor_interface/thought_toolkit/action_parser.py
- src/coauthor_interface/thought_toolkit/helper.py
- src/coauthor_interface/thought_toolkit/level_2_comparisons.py
- src/coauthor_interface/thought_toolkit/level_3_comparisons.py
- src/coauthor_interface/thought_toolkit/parser_all_levels.py
- src/coauthor_interface/thought_toolkit/parser_helper.py
- src/coauthor_interface/thought_toolkit/utils.py
- tests/test_api_server.py
- tests/test_helper.py
- tests/test_plugin.py
- uv.lock
Add all files from onedrive with fixed errors
**Note:** this work is still to get the files into github - not to address the swe issues
Prerequisite for the work in the following work item:
https://dev.azure.com/gt-sse-center/CoAuthor/_workitems/edit/686/
> 686 varun  add level one action analyzer

- src/coauthor_interface/backend/parse_all_consolidated.py
- tests/test_parse_all_consolidated.py
- tests/test_placeholder.py
post-experiment parser parses saved raw_keylogs and performs level 1, 2, and 3 analyses. This code was previously commented out and needed to be uncommented to run. This work moves this code into a separate file and refactors it into modular functions
> Refactor post experiment parser

- src/coauthor_interface/backend/PluginInterface.py
- src/coauthor_interface/thought_toolkit/level_3_plugins.py
- src/coauthor_interface/thought_toolkit/parser_all_levels.py
Refactor L3 analysis code to use plugin interface. Verified that output is the same before and after changes
https://dev.azure.com/gt-sse-center/CoAuthor/_workitems/edit/686/
> 686 varun  refactor l3 analysis to use plugin interface

- src/coauthor_interface/backend/api_server.py
- src/coauthor_interface/backend/helper.py
- src/coauthor_interface/backend/parsing.py
- src/coauthor_interface/frontend/index.html
- src/coauthor_interface/frontend/js/async.js
- src/coauthor_interface/frontend/js/editor.js
- tests/test_api_server.py
This work is to integrate the parse_logs route. This code has been brought over from the existing one drive
https://dev.azure.com/gt-sse-center/CoAuthor/_workitems/edit/697/
> Use parse logs route

- src/coauthor_interface/frontend/index.html
- src/coauthor_interface/frontend/js/async.js
- src/coauthor_interface/thought_toolkit/PluginInterface.py
Enable toasts instead of just alerts
https://dev.azure.com/gt-sse-center/CoAuthor/_workitems/edit/701/
> Enable toast functionality

- src/coauthor_interface/backend/api_server.py
Log active plugins per client session
> log active plugins per session

- tests/test_thought_toolkit_modules.py
add tests for helper functions
https://dev.azure.com/gt-sse-center/CoAuthor/_workitems/edit/702/
> [702]  add tests for helper functions

- src/coauthor_interface/backend/api_server.py
- src/coauthor_interface/backend/helper.py
- src/coauthor_interface/frontend/js/async.js
- src/coauthor_interface/thought_toolkit/parser_all_levels.py
- tests/test_api_server.py
- tests/test_thought_toolkit_modules.py
- fix bug with SameSentenceMergeAnalyzer
- update tests to use proper frontend raw keylog structure
- reestablish session independence
https://dev.azure.com/gt-sse-center/CoAuthor/_workitems/edit/705/
> 705 varun  refactor query route

- config/access_codes.csv
- src/coauthor_interface/backend/access_code.py
- src/coauthor_interface/backend/api_server.py
- src/coauthor_interface/frontend/js/async.js
- src/coauthor_interface/frontend/js/config.js
- src/coauthor_interface/frontend/js/helper.js
- src/coauthor_interface/frontend/js/index.js
- src/coauthor_interface/thought_toolkit/PluginInterface.py
- tests/test_api_server.py
- Add option to turn off interventions for a user through show_interventions variable in access_code file
- add query modification to intervention enum
https://dev.azure.com/gt-sse-center/CoAuthor/_workitems/edit/708/
> Varun 708  turn off interventions

- .github/workflows/standard.yaml
- pyproject.toml
- src/coauthor_interface/backend/reader.py
- tests/test_access_code.py
- tests/test_action_parser.py
- tests/test_parsing.py
- tests/test_reader.py
- Improve testing coverage by testing more helper functions and looking for uncovered statements in testing coverage report
- Move to pathlib
https://dev.azure.com/gt-sse-center/CoAuthor/_workitems/edit/702
> Improve testing coverage

- src/coauthor_interface/thought_toolkit/run_post_session_analysis.py
Address CI failures by fixing ruff linter error
> remove unused variable
